name: Run Zip tests

on:
  push:
  pull_request:
    branches-ignore: [master]

jobs:
  zip:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11-dev']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python scripts/ci/install
      - name: Run tests
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export PYTHONPATH='${{ github.workspace }}\botocore.zip'
          else
            export PYTHONPATH=${{ github.workspace }}/botocore.zip
          fi
          python -m zipfile -c botocore.zip botocore/
          python scripts/ci/run-zip-tests --with-cov --with-xdist --append-import
          rm botocore.zip
        shell: bash
