name: Run CRT tests
 
on:
  push:
  pull_request:
    branches-ignore: [master]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.15-dev']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: ${{ matrix.python-version == '3.15-dev' && '1' || '' }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '${{ matrix.python-version }}'
          cache: 'pip'
          allow-prereleases: true
      - name: Install dependencies and CRT
        run: |
          python scripts/ci/install --extras crt
      - name: Run tests
        run: |
          python scripts/ci/run-crt-tests --with-cov --with-xdist
